/**
 * Turns the two upstream sources (`models.md` + `cli.mjs`) into the snapshot
 * that ships with this package.
 *
 * Both the CI drift check and the runtime fallback consume the output of
 * `buildSnapshot`, so the rules below are the single definition of how a
 * Command Code model is described.
 */

import {
  collectBundleLiterals,
  parseTextOnlyModelIds,
} from "./bundle-literals.ts"
import { parseModelsDoc } from "./models-md.ts"
import { DEFAULT_MAX_OUTPUT, type SnapshotEntry } from "./types.ts"

export interface SnapshotResult {
  entries: SnapshotEntry[]
  /** Non-fatal upstream inconsistencies worth surfacing in CI. */
  warnings: string[]
}

/**
 * Builds the snapshot from raw upstream file contents.
 *
 * Field ownership:
 * - `name`, `context`, `cost`, `minPlan` come from the documented table;
 * - `reasoning`, `image`, `maxOutput` come from the CLI bundle literals;
 * - `efforts` comes from the table, and is cross-checked against the bundle.
 */
export function buildSnapshot(markdown: string, bundle: string): SnapshotResult {
  const documented = parseModelsDoc(markdown)
  const textOnly = new Set(parseTextOnlyModelIds(bundle))
  const literals = collectBundleLiterals(
    bundle,
    documented.map((model) => model.id),
  )
  const warnings: string[] = []

  const entries = documented.map((model): SnapshotEntry => {
    const bundleModel = literals.get(model.id)!

    if (bundleModel.efforts !== null && !sameEfforts(bundleModel.efforts, model.efforts)) {
      warnings.push(
        `effort levels differ for ${model.id}: docs=[${model.efforts.join(", ")}] bundle=[${bundleModel.efforts.join(", ")}] (using docs)`,
      )
    }

    // A documented effort list always implies a reasoning model; the reverse is
    // not true, because models without selectable levels still reason.
    const reasoning = bundleModel.reasoning || model.efforts.length > 0

    return {
      id: model.id,
      name: model.name,
      protocol: model.protocol,
      context: model.context,
      maxOutput: bundleModel.maxOutput ?? DEFAULT_MAX_OUTPUT,
      reasoning,
      efforts: model.efforts,
      image: !textOnly.has(model.id),
      cost: model.cost,
      minPlan: model.minPlan,
      status: model.context === null ? "deprecated" : "active",
    }
  })

  entries.sort((left, right) => left.id.localeCompare(right.id))
  return { entries, warnings }
}

function sameEfforts(left: readonly string[], right: readonly string[]): boolean {
  return left.length === right.length && left.every((effort, index) => effort === right[index])
}

export interface RenderOptions {
  packageVersion: string
  syncedAt?: string
}

/** Renders the snapshot as the contents of `src/catalog.generated.ts`. */
export function renderCatalogModule(entries: readonly SnapshotEntry[], options: RenderOptions): string {
  const body = entries.map(renderEntry).join(",\n")
  const syncedAt = options.syncedAt ?? new Date().toISOString().slice(0, 10)

  return `/**
 * Generated by \`npm run sync\`. Do not edit manually.
 *
 * Source: command-code@${options.packageVersion} (models.md + cli.mjs literals)
 * Synced: ${syncedAt}
 */

import type { SnapshotEntry } from "./types.ts"

export const COMMAND_CODE_CLI_VERSION = ${JSON.stringify(options.packageVersion)}

export const SNAPSHOT: readonly SnapshotEntry[] = [
${body},
]
`
}

function renderEntry(entry: SnapshotEntry): string {
  return [
    "  {",
    `    id: ${JSON.stringify(entry.id)},`,
    `    name: ${JSON.stringify(entry.name)},`,
    `    protocol: ${JSON.stringify(entry.protocol)},`,
    `    context: ${entry.context === null ? "null" : String(entry.context)},`,
    `    maxOutput: ${entry.maxOutput},`,
    `    reasoning: ${String(entry.reasoning)},`,
    `    efforts: [${entry.efforts.map((effort) => JSON.stringify(effort)).join(", ")}],`,
    `    image: ${String(entry.image)},`,
    `    cost: ${JSON.stringify(entry.cost)},`,
    `    minPlan: ${JSON.stringify(entry.minPlan)},`,
    `    status: ${JSON.stringify(entry.status)},`,
    "  }",
  ].join("\n")
}
